services:
  - type: web
    name: tarot-predictions
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --keep-alive 2 "app:create_app()"
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
    autoDeploy: true 